version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/" # Location of pubspec.yaml file
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/" # Location of .github directory
    schedule:
      interval: "monthly"
