targets:
  $default:
    builders:
      drift_dev:
        enabled: false
        options:
      drift_dev:analyzer:
        enabled: true
        options: &options
          store_date_time_values_as_text: true
          fatal_warnings: true
          sql:
            dialect: sqlite
            options:
              known_functions:
                regexp: "integer( text, text )"
              modules: [fts5]
          databases:
            AppDb: lib/src/external/database.dart
      drift_dev:modular:
        enabled: true
        options: *options