name: latin_reader
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1<4.0.0"

dependencies:
  collection: ^1.19.1
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  drift: ^2.28.0
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  intl: any
  logging: ^1.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  sqlite3: ^2.7.7
  sqlite3_flutter_libs: ^0.5.36
  stack_trace: ^1.12.1
  url_launcher: ^6.3.2
  yaml: ^3.1.3

dev_dependencies:
  build_runner: any
  build_verify: any
  drift_dev: ^2.28.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: any
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  generate: true # Enable generation of localized Strings from arb files.
  assets:
    - assets/images/
    - assets/preprocessed_data/
    - config.yaml