name: latin_reader
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3<4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.3
  flutter_riverpod: ^3.0.0-dev.3
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  collection: ^1.18.0
  csv: ^6.0.0
  package_info_plus: ^8.0.2
  riverpod_annotation: ^3.0.0-dev.3
  logging: ^1.2.0
  stack_trace: ^1.11.1
  cupertino_icons: ^1.0.8
  flutter_adaptive_scaffold: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  go_router_builder: any
  build_runner: any
  build_verify: any
  flutter_lints: ^4.0.0
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
  drift_dev: ^2.20.1

flutter:
  uses-material-design: true
  generate: true # Enable generation of localized Strings from arb files.
  assets:
    - assets/images/
    - assets/preprocessed_data/
