name: latin_reader
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3<4.0.0"

dependencies:
  collection: ^1.18.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  drift: ^2.22.1
  drift_flutter: ^0.2.2
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: 0.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.2.3
  intl: ^0.19.0
  logging: ^1.2.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  riverpod_annotation: ^2.6.1
  sqlite3: ^2.5.0
  sqlite3_flutter_libs: ^0.5.26
  stack_trace: ^1.11.1

dev_dependencies:
  build_runner: any
  build_verify: any
  drift_dev: ^2.22.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: any
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  generate: true # Enable generation of localized Strings from arb files.
  assets:
    - assets/images/
    - assets/preprocessed_data/
