name: latin_reader
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3<4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.1
  flutter_riverpod: ^2.5.1
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.0.0
  path: ^1.9.0
  collection: ^1.18.0
  csv: ^6.0.0
  package_info_plus: ^8.0.0
  riverpod_annotation: ^2.3.5
  logging: ^1.2.0
  stack_trace: ^1.11.1
  cupertino_icons: ^1.0.8
  flutter_adaptive_scaffold: ^0.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  go_router_builder: any
  build_runner: any
  build_verify: any
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  generate: true # Enable generation of localized Strings from arb files.
  assets:
    - assets/images/
    - assets/preprocessed_data/
