// GENERATED FILE - DO NOT EDIT BY HAND
// Run `dart run tool/generate_fonts.dart` to update this list.

const Set<String> latinExtFonts = {
  'ABeeZee',
  'ADLaM Display',
  'AR One Sans',
  'Abhaya Libre',
  'Aboreto',
  'Abril Fatface',
  'Abyssinica SIL',
  'Aclonica',
  'Advent Pro',
  'Afacad',
  'Afacad Flux',
  'Agbalumo',
  'Agdasima',
  'Agu Display',
  'Aguafina Script',
  'Akatab',
  'Akaya Kanadaka',
  'Akaya Telivigala',
  'Akronim',
  'Akshar',
  'Akt',
  'Aladin',
  'Alan Sans',
  'Alata',
  'Alatsi',
  'Albert Sans',
  'Alegreya',
  'Alegreya SC',
  'Alegreya Sans',
  'Alegreya Sans SC',
  'Aleo',
  'Alex Brush',
  'Alexandria',
  'Alfa Slab One',
  'Alice',
  'Alien Block',
  'Alike',
  'Alike Angular',
  'Alkalami',
  'Alkatra',
  'Allan',
  'Allison',
  'Allura',
  'Almendra',
  'Almendra Display',
  'Alumni Sans',
  'Alumni Sans Collegiate One',
  'Alumni Sans Inline One',
  'Alumni Sans Pinstripe',
  'Alumni Sans SC',
  'Alyamama',
  'Amarante',
  'Amarna',
  'Amatic SC',
  'Amiko',
  'Amiri',
  'Amita',
  'Anaheim',
  'Ancizar Sans',
  'Ancizar Serif',
  'Andada Pro',
  'Andika',
  'Anek Bangla',
  'Anek Devanagari',
  'Anek Gujarati',
  'Anek Gurmukhi',
  'Anek Kannada',
  'Anek Latin',
  'Anek Malayalam',
  'Anek Odia',
  'Anek Tamil',
  'Anek Telugu',
  'Annapurna SIL',
  'Annie Use Your Telescope',
  'Anonymous Pro',
  'Anta',
  'Anton',
  'Anton SC',
  'Antonio',
  'Anuphan',
  'Anybody',
  'Aoboshi One',
  'Arbutus',
  'Arbutus Slab',
  'Architects Daughter',
  'Archivo',
  'Archivo Black',
  'Archivo Narrow',
  'Are You Serious',
  'Aref Ruqaa',
  'Aref Ruqaa Ink',
  'Arima',
  'Arimo',
  'Arizonia',
  'Armata',
  'Arsenal',
  'Arsenal SC',
  'Arya',
  'Asap',
  'Asap Condensed',
  'Asar',
  'Asimovian',
  'Asset',
  'Assistant',
  'Athiti',
  'Atkinson Hyperlegible',
  'Atkinson Hyperlegible Mono',
  'Atkinson Hyperlegible Next',
  'Atma',
  'Atomic Age',
  'Audiowide',
  'Autour One',
  'Average',
  'Average Sans',
  'Averia Gruesa Libre',
  'Azeret Mono',
  'BIZ UDGothic',
  'BIZ UDMincho',
  'BIZ UDPGothic',
  'BIZ UDPMincho',
  'Babylonica',
  'Bacasime Antique',
  'Bad Script',
  'Badeen Display',
  'Bagel Fat One',
  'Bahiana',
  'Bahianita',
  'Bai Jamjuree',
  'Bakbak One',
  'Ballet',
  'Baloo 2',
  'Baloo Bhai 2',
  'Baloo Bhaijaan 2',
  'Baloo Bhaina 2',
  'Baloo Chettan 2',
  'Baloo Da 2',
  'Baloo Paaji 2',
  'Baloo Tamma 2',
  'Baloo Tammudu 2',
  'Baloo Thambi 2',
  'Balsamiq Sans',
  'Bangers',
  'Barlow',
  'Barlow Condensed',
  'Barlow Semi Condensed',
  'Barriecito',
  'Barrio',
  'Basic',
  'Baskervville',
  'Baskervville SC',
  'Be Vietnam Pro',
  'Beau Rivage',
  'Bebas Neue',
  'Beiruti',
  'Belanosima',
  'Bellefair',
  'Belleza',
  'Bellota',
  'Bellota Text',
  'BenchNine',
  'Benne',
  'Bentham',
  'Berkshire Swash',
  'Besley',
  'Betania Patmos',
  'Betania Patmos GDL',
  'Betania Patmos In',
  'Betania Patmos In GDL',
  'Bevan',
  'BhuTuka Expanded One',
  'Big Shoulders',
  'Big Shoulders Inline',
  'Big Shoulders Stencil',
  'Bigelow Rules',
  'Bilbo',
  'Bilbo Swash Caps',
  'BioRhyme',
  'BioRhyme Expanded',
  'Birthstone',
  'Birthstone Bounce',
  'Biryani',
  'Bitcount',
  'Bitcount Grid Double',
  'Bitcount Grid Double Ink',
  'Bitcount Grid Single',
  'Bitcount Grid Single Ink',
  'Bitcount Ink',
  'Bitcount Prop Double',
  'Bitcount Prop Double Ink',
  'Bitcount Prop Single',
  'Bitcount Prop Single Ink',
  'Bitcount Single',
  'Bitcount Single Ink',
  'Bitter',
  'Black Ops One',
  'Blaka',
  'Blaka Hollow',
  'Blaka Ink',
  'Blinker',
  'Bodoni Moda',
  'Bodoni Moda SC',
  'Boldonse',
  'Bona Nova',
  'Bona Nova SC',
  'Bonheur Royale',
  'Borel',
  'Bowlby One SC',
  'Bpmf Huninn',
  'Bpmf Iansui',
  'Bpmf Zihi Kai Std',
  'Braah One',
  'Bree Serif',
  'Bricolage Grotesque',
  'Bruno Ace',
  'Bruno Ace SC',
  'Brygada 1918',
  'Bubblegum Sans',
  'Bubbler One',
  'Buenard',
  'Bungee',
  'Bungee Hairline',
  'Bungee Inline',
  'Bungee Outline',
  'Bungee Shade',
  'Bungee Spice',
  'Bungee Tint',
  'Butcherman',
  'Butterfly Kids',
  'Bytesized',
  'Cabin',
  'Cabin Condensed',
  'Cactus Classical Serif',
  'Cairo',
  'Cairo Play',
  'Cal Sans',
  'Caladea',
  'Calistoga',
  'Cambay',
  'Cambo',
  'Cantarell',
  'Cantata One',
  'Cantora One',
  'Caprasimo',
  'Capriola',
  'Caramel',
  'Carattere',
  'Cardo',
  'Carlito',
  'Cascadia Code',
  'Cascadia Mono',
  'Castoro',
  'Castoro Titling',
  'Catamaran',
  'Caudex',
  'Cause',
  'Caveat',
  'Caveat Brush',
  'Ceviche One',
  'Chakra Petch',
  'Changa',
  'Chango',
  'Charis SIL',
  'Charm',
  'Charmonman',
  'Chau Philomene One',
  'Chela One',
  'Chelsea Market',
  'Cherish',
  'Cherry Bomb One',
  'Cherry Swash',
  'Chicle',
  'Chilanka',
  'Chiron GoRound TC',
  'Chiron Hei HK',
  'Chiron Sung HK',
  'Chivo',
  'Chivo Mono',
  'Chocolate Classical Sans',
  'Chokokutai',
  'Chonburi',
  'Cinzel',
  'Cinzel Decorative',
  'Clicker Script',
  'Climate Crisis',
  'Coda',
  'Codystar',
  'Coiny',
  'Combo',
  'Comfortaa',
  'Comforter',
  'Comforter Brush',
  'Comic Relief',
  'Comme',
  'Commissioner',
  'Concert One',
  'Condiment',
  'Convergence',
  'Coral Pixels',
  'Corben',
  'Corinthia',
  'Cormorant',
  'Cormorant Garamond',
  'Cormorant Infant',
  'Cormorant SC',
  'Cormorant Unicase',
  'Cormorant Upright',
  'Cossette Texte',
  'Cossette Titre',
  'Courgette',
  'Courier Prime',
  'Cousine',
  'Coustard',
  'Covered By Your Grace',
  'Crete Round',
  'Crimson Pro',
  'Crimson Text',
  'Croissant One',
  'Crushed',
  'Cuprum',
  'Cutive',
  'Cutive Mono',
  'DM Mono',
  'DM Sans',
  'DM Serif Display',
  'DM Serif Text',
  'Dai Banna SIL',
  'Damion',
  'Dancing Script',
  'Danfo',
  'Darker Grotesque',
  'Darumadrop One',
  'Datatype',
  'David Libre',
  'Dekko',
  'Dela Gothic One',
  'Delicious Handrawn',
  'Denk One',
  'Devonshire',
  'Didact Gothic',
  'Diphylleia',
  'Diplomata',
  'Diplomata SC',
  'Domine',
  'Donegal One',
  'Dongle',
  'Doppio One',
  'Dosis',
  'DotGothic16',
  'Doto',
  'Dr Sugiyama',
  'Duru Sans',
  'DynaPuff',
  'Dynalight',
  'EB Garamond',
  'Eagle Lake',
  'Eater',
  'Economica',
  'Eczar',
  'Edu AU VIC WA NT Arrows',
  'Edu AU VIC WA NT Dots',
  'Edu AU VIC WA NT Guides',
  'Edu AU VIC WA NT Hand',
  'Edu AU VIC WA NT Pre',
  'Edu NSW ACT Cursive',
  'Edu NSW ACT Hand Pre',
  'Edu QLD Hand',
  'Edu SA Hand',
  'Edu VIC WA NT Hand',
  'Edu VIC WA NT Hand Pre',
  'El Messiri',
  'Elms Sans',
  'Elsie',
  'Elsie Swash Caps',
  'Emblema One',
  'Emilys Candy',
  'Encode Sans',
  'Encode Sans Condensed',
  'Encode Sans Expanded',
  'Encode Sans SC',
  'Encode Sans Semi Condensed',
  'Encode Sans Semi Expanded',
  'Engagement',
  'Englebert',
  'Enriqueta',
  'Ephesis',
  'Epilogue',
  'Epunda Sans',
  'Epunda Slab',
  'Erica One',
  'Esteban',
  'Estedad',
  'Estonia',
  'Euphoria Script',
  'Ewert',
  'Exile',
  'Exo',
  'Exo 2',
  'Expletus Sans',
  'Explora',
  'Faculty Glyphic',
  'Fahkwang',
  'Familjen Grotesk',
  'Fanwood Text',
  'Farro',
  'Farsan',
  'Fascinate',
  'Fascinate Inline',
  'Faster One',
  'Fauna One',
  'Faustina',
  'Felipa',
  'Fenix',
  'Festive',
  'Figtree',
  'Finlandica Headline',
  'Finlandica Text',
  'Fira Code',
  'Fira Mono',
  'Fira Sans',
  'Fira Sans Condensed',
  'Fira Sans Extra Condensed',
  'Fjalla One',
  'Flavors',
  'Fleur De Leah',
  'Flow Block',
  'Flow Circular',
  'Flow Rounded',
  'Foldit',
  'Fondamento',
  'Forum',
  'Fragment Mono',
  'Francois One',
  'Frank Ruhl Libre',
  'Fraunces',
  'Freckle Face',
  'Fredericka the Great',
  'Fredoka',
  'Freeman',
  'Fresca',
  'Fruktur',
  'Fuggles',
  'Funnel Display',
  'Funnel Sans',
  'Fustat',
  'Fuzzy Bubbles',
  'Ga Maamli',
  'Gabarito',
  'Gabriela',
  'Gafata',
  'Gajraj One',
  'Galindo',
  'Gantari',
  'Gasoek One',
  'Geist',
  'Geist Mono',
  'Gelasio',
  'Gemunu Libre',
  'Genos',
  'Gentium Book Plus',
  'Gentium Plus',
  'Geologica',
  'Geom',
  'Georama',
  'Gideon Roman',
  'Gidole',
  'Gidugu',
  'Gilda Display',
  'Girassol',
  'Give You Glory',
  'Glass Antiqua',
  'Glegoo',
  'Gloock',
  'Gloria Hallelujah',
  'Glory',
  'Gluten',
  'Goldman',
  'Golos Text',
  'Google Sans',
  'Google Sans Code',
  'Google Sans Flex',
  'Gothic A1',
  'Gotu',
  'Gowun Batang',
  'Gowun Dodum',
  'Grand Hotel',
  'Grandiflora One',
  'Grandstander',
  'Grape Nuts',
  'Great Vibes',
  'Grechen Fuemen',
  'Grenze',
  'Grenze Gotisch',
  'Grey Qo',
  'Griffy',
  'Gruppo',
  'Gudea',
  'Gulzar',
  'Gurajada',
  'Gwendolyn',
  'Habibi',
  'Hachi Maru Pop',
  'Hahmlet',
  'Halant',
  'Hammersmith One',
  'Hanalei',
  'Hanalei Fill',
  'Handjet',
  'Hanken Grotesk',
  'Happy Monkey',
  'Harmattan',
  'Headland One',
  'Hedvig Letters Sans',
  'Hedvig Letters Serif',
  'Heebo',
  'Hepta Slab',
  'Herr Von Muellerhoff',
  'Hina Mincho',
  'Hind',
  'Hind Guntur',
  'Hind Madurai',
  'Hind Mysuru',
  'Hind Siliguri',
  'Hind Vadodara',
  'Holtwood One SC',
  'Honk',
  'Host Grotesk',
  'Hubballi',
  'Hubot Sans',
  'Huninn',
  'Hurricane',
  'IBM Plex Mono',
  'IBM Plex Sans',
  'IBM Plex Sans Arabic',
  'IBM Plex Sans Condensed',
  'IBM Plex Sans Devanagari',
  'IBM Plex Sans Hebrew',
  'IBM Plex Sans JP',
  'IBM Plex Sans KR',
  'IBM Plex Sans Thai',
  'IBM Plex Sans Thai Looped',
  'IBM Plex Serif',
  'Iansui',
  'Ibarra Real Nova',
  'Imbue',
  'Imperial Script',
  'Imprima',
  'Inclusive Sans',
  'Inconsolata',
  'Inder',
  'Indie Flower',
  'Ingrid Darling',
  'Inika',
  'Inknut Antiqua',
  'Inria Sans',
  'Inria Serif',
  'Inspiration',
  'Instrument Sans',
  'Instrument Serif',
  'Intel One Mono',
  'Inter',
  'Inter Tight',
  'Iosevka Charon',
  'Iosevka Charon Mono',
  'Island Moments',
  'Istok Web',
  'Italianno',
  'Itim',
  'Jacquard 12',
  'Jacquard 12 Charted',
  'Jacquard 24',
  'Jacquard 24 Charted',
  'Jacquarda Bastarda 9',
  'Jacquarda Bastarda 9 Charted',
  'Jaini',
  'Jaini Purva',
  'Jaldi',
  'Jaro',
  'Jersey 10',
  'Jersey 10 Charted',
  'Jersey 15',
  'Jersey 15 Charted',
  'Jersey 20',
  'Jersey 20 Charted',
  'Jersey 25',
  'Jersey 25 Charted',
  'JetBrains Mono',
  'Jim Nightshade',
  'Joan',
  'Jockey One',
  'Jolly Lodger',
  'Jomhuria',
  'Josefin Sans',
  'Jost',
  'Joti One',
  'Judson',
  'Julee',
  'Julius Sans One',
  'Jura',
  'Just Another Hand',
  'Just Me Again Down Here',
  'K2D',
  'Kablammo',
  'Kaisei Decol',
  'Kaisei HarunoUmi',
  'Kaisei Opti',
  'Kaisei Tokumin',
  'Kalam',
  'Kalnia',
  'Kalnia Glaze',
  'Kameron',
  'Kanit',
  'Kantumruy Pro',
  'Kapakana',
  'Karantina',
  'Karla',
  'Karma',
  'Katibeh',
  'Kaushan Script',
  'Kavivanar',
  'Kavoon',
  'Kay Pho Du',
  'Kdam Thmor Pro',
  'Keania One',
  'Kelly Slab',
  'Khand',
  'Khula',
  'Kings',
  'Kite One',
  'Kiwi Maru',
  'Klee One',
  'Knewave',
  'KoHo',
  'Kodchasan',
  'Kode Mono',
  'Kolker Brush',
  'Konkhmer Sleokchher',
  'Kosugi',
  'Kosugi Maru',
  'Kotta One',
  'Kreon',
  'Krona One',
  'Krub',
  'Kufam',
  'Kulim Park',
  'Kumar One',
  'Kumar One Outline',
  'Kumbh Sans',
  'Kurale',
  'LINE Seed JP',
  'LXGW Marker Gothic',
  'LXGW WenKai Mono TC',
  'LXGW WenKai TC',
  'La Belle Aurore',
  'Labrada',
  'Laila',
  'Lalezar',
  'Lancelot',
  'Langar',
  'Lateef',
  'Lato',
  'Lavishly Yours',
  'League Gothic',
  'League Spartan',
  'Ledger',
  'Lekton',
  'Lemon',
  'Lemonada',
  'Lexend',
  'Lexend Deca',
  'Lexend Exa',
  'Lexend Giga',
  'Lexend Mega',
  'Lexend Peta',
  'Lexend Tera',
  'Lexend Zetta',
  'Libertinus Keyboard',
  'Libertinus Mono',
  'Libertinus Sans',
  'Libertinus Serif',
  'Libertinus Serif Display',
  'Libre Baskerville',
  'Libre Bodoni',
  'Libre Caslon Display',
  'Libre Caslon Text',
  'Libre Franklin',
  'Licorice',
  'Life Savers',
  'Lilex',
  'Lilita One',
  'Lily Script One',
  'Limelight',
  'Linden Hill',
  'Lisu Bosa',
  'Liter',
  'Literata',
  'Livvic',
  'Lobster',
  'Lora',
  'Love Light',
  'Love Ya Like A Sister',
  'Loved by the King',
  'Lovers Quarrel',
  'Luckiest Guy',
  'Lugrasimo',
  'Lumanosimo',
  'Lunasima',
  'Luxurious Roman',
  'Luxurious Script',
  'M PLUS 1',
  'M PLUS 1 Code',
  'M PLUS 1p',
  'M PLUS 2',
  'M PLUS Code Latin',
  'M PLUS Rounded 1c',
  'M PLUS U',
  'Mada',
  'Madimi One',
  'Magra',
  'Maiden Orange',
  'Maitree',
  'Major Mono Display',
  'Mako',
  'Mali',
  'Maname',
  'Manjari',
  'Manrope',
  'Mansalva',
  'Manuale',
  'Manufacturing Consent',
  'Marcellus',
  'Marcellus SC',
  'Marck Script',
  'Margarine',
  'Marhey',
  'Markazi Text',
  'Marmelad',
  'Martel',
  'Martel Sans',
  'Martian Mono',
  'Matangi',
  'Mate',
  'Mate SC',
  'Matemasie',
  'Maven Pro',
  'McLaren',
  'Mea Culpa',
  'Meddon',
  'MedievalSharp',
  'Megrim',
  'Meie Script',
  'Menbere',
  'Meow Script',
  'Merienda',
  'Merriweather',
  'Merriweather Sans',
  'Metal Mania',
  'Metamorphous',
  'Metrophobic',
  'Michroma',
  'Micro 5',
  'Micro 5 Charted',
  'Milonga',
  'Mina',
  'Mingzat',
  'Miranda Sans',
  'Miriam Libre',
  'Mirza',
  'Miss Fajardose',
  'Mitr',
  'Modak',
  'Modern Antiqua',
  'Moderustic',
  'Mogra',
  'Mohave',
  'Moirai One',
  'Molengo',
  'Molle',
  'Momo Signature',
  'Momo Trust Display',
  'Momo Trust Sans',
  'Mona Sans',
  'Monda',
  'Monofett',
  'Monomakh',
  'Monomaniac One',
  'Monoton',
  'Monsieur La Doulaise',
  'Montagu Slab',
  'MonteCarlo',
  'Montez',
  'Montserrat',
  'Montserrat Alternates',
  'Montserrat Underline',
  'Moo Lah Lah',
  'Mooli',
  'Moon Dance',
  'Mouse Memoirs',
  'Mozilla Headline',
  'Mozilla Text',
  'Mr Bedfort',
  'Mr Dafoe',
  'Mr De Haviland',
  'Mrs Saint Delafield',
  'Mrs Sheppards',
  'Ms Madi',
  'Mukta',
  'Mukta Mahee',
  'Mukta Malar',
  'Mukta Vaani',
  'Mulish',
  'Murecho',
  'MuseoModerno',
  'My Soul',
  'Mynerve',
  'Mystery Quest',
  'Nabla',
  'Namdhinggo',
  'Narnoor',
  'Nata Sans',
  'National Park',
  'Neonderthaw',
  'Nerko One',
  'Neuton',
  'New Amsterdam',
  'New Rocker',
  'New Tegomin',
  'News Cycle',
  'Newsreader',
  'Niconne',
  'Niramit',
  'Nobile',
  'Norican',
  'Nosifer',
  'Noticia Text',
  'Noto Kufi Arabic',
  'Noto Music',
  'Noto Naskh Arabic',
  'Noto Nastaliq Urdu',
  'Noto Rashi Hebrew',
  'Noto Sans',
  'Noto Sans Adlam',
  'Noto Sans Adlam Unjoined',
  'Noto Sans Anatolian Hieroglyphs',
  'Noto Sans Arabic',
  'Noto Sans Armenian',
  'Noto Sans Avestan',
  'Noto Sans Balinese',
  'Noto Sans Bamum',
  'Noto Sans Bassa Vah',
  'Noto Sans Batak',
  'Noto Sans Bengali',
  'Noto Sans Bhaiksuki',
  'Noto Sans Brahmi',
  'Noto Sans Buginese',
  'Noto Sans Buhid',
  'Noto Sans Canadian Aboriginal',
  'Noto Sans Carian',
  'Noto Sans Caucasian Albanian',
  'Noto Sans Chakma',
  'Noto Sans Cham',
  'Noto Sans Cherokee',
  'Noto Sans Chorasmian',
  'Noto Sans Coptic',
  'Noto Sans Cuneiform',
  'Noto Sans Cypriot',
  'Noto Sans Cypro Minoan',
  'Noto Sans Deseret',
  'Noto Sans Devanagari',
  'Noto Sans Display',
  'Noto Sans Duployan',
  'Noto Sans Egyptian Hieroglyphs',
  'Noto Sans Elbasan',
  'Noto Sans Elymaic',
  'Noto Sans Ethiopic',
  'Noto Sans Georgian',
  'Noto Sans Glagolitic',
  'Noto Sans Gothic',
  'Noto Sans Grantha',
  'Noto Sans Gujarati',
  'Noto Sans Gunjala Gondi',
  'Noto Sans Gurmukhi',
  'Noto Sans HK',
  'Noto Sans Hanifi Rohingya',
  'Noto Sans Hanunoo',
  'Noto Sans Hatran',
  'Noto Sans Hebrew',
  'Noto Sans Imperial Aramaic',
  'Noto Sans Indic Siyaq Numbers',
  'Noto Sans Inscriptional Pahlavi',
  'Noto Sans Inscriptional Parthian',
  'Noto Sans JP',
  'Noto Sans Javanese',
  'Noto Sans KR',
  'Noto Sans Kaithi',
  'Noto Sans Kannada',
  'Noto Sans Kawi',
  'Noto Sans Kayah Li',
  'Noto Sans Kharoshthi',
  'Noto Sans Khmer',
  'Noto Sans Khojki',
  'Noto Sans Khudawadi',
  'Noto Sans Lao',
  'Noto Sans Lao Looped',
  'Noto Sans Lepcha',
  'Noto Sans Limbu',
  'Noto Sans Linear A',
  'Noto Sans Linear B',
  'Noto Sans Lisu',
  'Noto Sans Lydian',
  'Noto Sans Mahajani',
  'Noto Sans Malayalam',
  'Noto Sans Mandaic',
  'Noto Sans Manichaean',
  'Noto Sans Marchen',
  'Noto Sans Masaram Gondi',
  'Noto Sans Mayan Numerals',
  'Noto Sans Medefaidrin',
  'Noto Sans Meetei Mayek',
  'Noto Sans Mende Kikakui',
  'Noto Sans Meroitic',
  'Noto Sans Miao',
  'Noto Sans Modi',
  'Noto Sans Mongolian',
  'Noto Sans Mono',
  'Noto Sans Mro',
  'Noto Sans Multani',
  'Noto Sans Myanmar',
  'Noto Sans NKo',
  'Noto Sans NKo Unjoined',
  'Noto Sans Nabataean',
  'Noto Sans Nag Mundari',
  'Noto Sans Nandinagari',
  'Noto Sans New Tai Lue',
  'Noto Sans Newa',
  'Noto Sans Nushu',
  'Noto Sans Ogham',
  'Noto Sans Ol Chiki',
  'Noto Sans Old Hungarian',
  'Noto Sans Old Italic',
  'Noto Sans Old North Arabian',
  'Noto Sans Old Permic',
  'Noto Sans Old Persian',
  'Noto Sans Old Sogdian',
  'Noto Sans Old South Arabian',
  'Noto Sans Old Turkic',
  'Noto Sans Oriya',
  'Noto Sans Osage',
  'Noto Sans Osmanya',
  'Noto Sans Pahawh Hmong',
  'Noto Sans Palmyrene',
  'Noto Sans Pau Cin Hau',
  'Noto Sans PhagsPa',
  'Noto Sans Phoenician',
  'Noto Sans Psalter Pahlavi',
  'Noto Sans Rejang',
  'Noto Sans Runic',
  'Noto Sans SC',
  'Noto Sans Samaritan',
  'Noto Sans Saurashtra',
  'Noto Sans Sharada',
  'Noto Sans Shavian',
  'Noto Sans Siddham',
  'Noto Sans SignWriting',
  'Noto Sans Sinhala',
  'Noto Sans Sogdian',
  'Noto Sans Sora Sompeng',
  'Noto Sans Soyombo',
  'Noto Sans Sundanese',
  'Noto Sans Sunuwar',
  'Noto Sans Syloti Nagri',
  'Noto Sans Symbols',
  'Noto Sans Symbols 2',
  'Noto Sans Syriac',
  'Noto Sans Syriac Eastern',
  'Noto Sans Syriac Western',
  'Noto Sans TC',
  'Noto Sans Tagalog',
  'Noto Sans Tagbanwa',
  'Noto Sans Tai Le',
  'Noto Sans Tai Tham',
  'Noto Sans Tai Viet',
  'Noto Sans Takri',
  'Noto Sans Tamil',
  'Noto Sans Tamil Supplement',
  'Noto Sans Tangsa',
  'Noto Sans Telugu',
  'Noto Sans Thaana',
  'Noto Sans Thai',
  'Noto Sans Thai Looped',
  'Noto Sans Tifinagh',
  'Noto Sans Tirhuta',
  'Noto Sans Ugaritic',
  'Noto Sans Vai',
  'Noto Sans Vithkuqi',
  'Noto Sans Wancho',
  'Noto Sans Warang Citi',
  'Noto Sans Yi',
  'Noto Sans Zanabazar Square',
  'Noto Serif',
  'Noto Serif Ahom',
  'Noto Serif Armenian',
  'Noto Serif Balinese',
  'Noto Serif Bengali',
  'Noto Serif Devanagari',
  'Noto Serif Display',
  'Noto Serif Dives Akuru',
  'Noto Serif Dogra',
  'Noto Serif Ethiopic',
  'Noto Serif Georgian',
  'Noto Serif Grantha',
  'Noto Serif Gujarati',
  'Noto Serif Gurmukhi',
  'Noto Serif HK',
  'Noto Serif Hebrew',
  'Noto Serif Hentaigana',
  'Noto Serif JP',
  'Noto Serif KR',
  'Noto Serif Kannada',
  'Noto Serif Khitan Small Script',
  'Noto Serif Khmer',
  'Noto Serif Khojki',
  'Noto Serif Lao',
  'Noto Serif Makasar',
  'Noto Serif Malayalam',
  'Noto Serif Old Uyghur',
  'Noto Serif Oriya',
  'Noto Serif Ottoman Siyaq',
  'Noto Serif SC',
  'Noto Serif Sinhala',
  'Noto Serif TC',
  'Noto Serif Tamil',
  'Noto Serif Tangut',
  'Noto Serif Telugu',
  'Noto Serif Thai',
  'Noto Serif Tibetan',
  'Noto Serif Todhri',
  'Noto Serif Toto',
  'Noto Serif Vithkuqi',
  'Noto Serif Yezidi',
  'Noto Traditional Nushu',
  'Noto Znamenny Musical Notation',
  'Nova Cut',
  'Nova Flat',
  'Nova Mono',
  'Nova Oval',
  'Nova Round',
  'Nova Script',
  'Nova Slim',
  'Nova Square',
  'Nunito',
  'Nunito Sans',
  'Nuosu SIL',
  'Offside',
  'Oi',
  'Ojuju',
  'Old Standard TT',
  'Oldenburg',
  'Ole',
  'Oleo Script',
  'Oleo Script Swash Caps',
  'Onest',
  'Oooh Baby',
  'Open Sans',
  'Oranienbaum',
  'Orbit',
  'Oregano',
  'Orelega One',
  'Orienta',
  'Original Surfer',
  'Oswald',
  'Outfit',
  'Over the Rainbow',
  'Overlock',
  'Overlock SC',
  'Overpass',
  'Overpass Mono',
  'Oxanium',
  'Oxygen',
  'Oxygen Mono',
  'PT Mono',
  'PT Sans',
  'PT Sans Caption',
  'PT Sans Narrow',
  'PT Serif',
  'PT Serif Caption',
  'Pacifico',
  'Padauk',
  'Padyakke Expanded One',
  'Palanquin',
  'Palanquin Dark',
  'Pangolin',
  'Paprika',
  'Parastoo',
  'Parisienne',
  'Parkinsans',
  'Passero One',
  'Passion One',
  'Passions Conflict',
  'Pathway Extreme',
  'Pathway Gothic One',
  'Patrick Hand',
  'Patrick Hand SC',
  'Pattaya',
  'Pavanam',
  'Paytone One',
  'Peralta',
  'Petemoss',
  'Petit Formal Script',
  'Petrona',
  'Philosopher',
  'Phudu',
  'Piazzolla',
  'Piedra',
  'Pinyon Script',
  'Pirata One',
  'Pixelify Sans',
  'Plaster',
  'Platypi',
  'Play',
  'Playball',
  'Playfair',
  'Playfair Display',
  'Playfair Display SC',
  'Playpen Sans',
  'Playpen Sans Arabic',
  'Playpen Sans Deva',
  'Playpen Sans Hebrew',
  'Playpen Sans Thai',
  'Pliant',
  'Plus Jakarta Sans',
  'Podkova',
  'Poetsen One',
  'Poiret One',
  'Poltawski Nowy',
  'Poly',
  'Pontano Sans',
  'Poppins',
  'Potta One',
  'Pragati Narrow',
  'Praise',
  'Press Start 2P',
  'Pridi',
  'Princess Sofia',
  'Prompt',
  'Prosto One',
  'Protest Guerrilla',
  'Protest Revolution',
  'Protest Riot',
  'Protest Strike',
  'Proza Libre',
  'Public Sans',
  'Puppies Play',
  'Purple Purse',
  'Quando',
  'Quattrocento',
  'Quattrocento Sans',
  'Questrial',
  'Quicksand',
  'Quintessential',
  'Qwigley',
  'Qwitcher Grypen',
  'REM',
  'Racing Sans One',
  'Radio Canada',
  'Radio Canada Big',
  'Radley',
  'Rajdhani',
  'Rakkas',
  'Raleway',
  'Raleway Dots',
  'Rambla',
  'Rammetto One',
  'Rampart One',
  'Ranchers',
  'Ranga',
  'Rasa',
  'Readex Pro',
  'Recursive',
  'Red Hat Display',
  'Red Hat Mono',
  'Red Hat Text',
  'Red Rose',
  'Redacted',
  'Redacted Script',
  'Reddit Mono',
  'Reddit Sans',
  'Reddit Sans Condensed',
  'Redressed',
  'Reem Kufi',
  'Reem Kufi Fun',
  'Reem Kufi Ink',
  'Reggae One',
  'Rethink Sans',
  'Revalia',
  'Rhodium Libre',
  'Ribeye',
  'Ribeye Marrow',
  'Righteous',
  'Risque',
  'Road Rage',
  'Roboto',
  'Roboto Condensed',
  'Roboto Flex',
  'Roboto Mono',
  'Roboto Serif',
  'Roboto Slab',
  'RocknRoll One',
  'Rokkitt',
  'Romanesco',
  'Ropa Sans',
  'Rosario',
  'Rosarivo',
  'Rowdies',
  'Rozha One',
  'Rubik',
  'Rubik 80s Fade',
  'Rubik Beastly',
  'Rubik Broken Fax',
  'Rubik Bubbles',
  'Rubik Burned',
  'Rubik Dirt',
  'Rubik Distressed',
  'Rubik Doodle Shadow',
  'Rubik Doodle Triangles',
  'Rubik Gemstones',
  'Rubik Glitch',
  'Rubik Glitch Pop',
  'Rubik Iso',
  'Rubik Lines',
  'Rubik Maps',
  'Rubik Marker Hatch',
  'Rubik Maze',
  'Rubik Microbe',
  'Rubik Mono One',
  'Rubik Moonrocks',
  'Rubik Pixels',
  'Rubik Puddles',
  'Rubik Scribble',
  'Rubik Spray Paint',
  'Rubik Storm',
  'Rubik Vinyl',
  'Rubik Wet Paint',
  'Ruda',
  'Rufina',
  'Ruge Boogie',
  'Ruluko',
  'Rum Raisin',
  'Ruslan Display',
  'Russo One',
  'Ruthie',
  'Ruwudu',
  'Rye',
  'SN Pro',
  'STIX Two Text',
  'SUSE',
  'SUSE Mono',
  'Sacramento',
  'Sail',
  'Saira',
  'Saira Condensed',
  'Saira Extra Condensed',
  'Saira Semi Condensed',
  'Saira Stencil',
  'Sanchez',
  'Sancreek',
  'Sankofa Display',
  'Sansation',
  'Sansita',
  'Sansita Swashed',
  'Sarabun',
  'Sarala',
  'Sarina',
  'Sarpanch',
  'Sassy Frass',
  'Savate',
  'Sawarabi Gothic',
  'Sawarabi Mincho',
  'Scada',
  'Scheherazade New',
  'Schibsted Grotesk',
  'Science Gothic',
  'Scope One',
  'Seaweed Script',
  'Secular One',
  'Sedan',
  'Sedan SC',
  'Sedgwick Ave',
  'Sedgwick Ave Display',
  'Sekuya',
  'Sen',
  'Send Flowers',
  'Sevillana',
  'Seymour One',
  'Shadows Into Light',
  'Shadows Into Light Two',
  'Shafarik',
  'Shalimar',
  'Shantell Sans',
  'Shanti',
  'Share',
  'Shippori Antique',
  'Shippori Antique B1',
  'Shippori Mincho',
  'Shippori Mincho B1',
  'Shojumaru',
  'Shrikhand',
  'Sigmar',
  'Sigmar One',
  'Signika',
  'Signika Negative',
  'Silkscreen',
  'Simonetta',
  'Sintony',
  'Six Caps',
  'Sixtyfour',
  'Sixtyfour Convergence',
  'Skranji',
  'Slabo 13px',
  'Slabo 27px',
  'Slackside One',
  'Smokum',
  'Smooch',
  'Smooch Sans',
  'Sniglet',
  'Snowburst One',
  'Sofia Sans',
  'Sofia Sans Condensed',
  'Sofia Sans Extra Condensed',
  'Sofia Sans Semi Condensed',
  'Solitreo',
  'Sometype Mono',
  'Sono',
  'Sonsie One',
  'Sora',
  'Sorts Mill Goudy',
  'Sour Gummy',
  'Source Code Pro',
  'Source Sans 3',
  'Source Serif 4',
  'Space Grotesk',
  'Space Mono',
  'Special Elite',
  'Special Gothic',
  'Special Gothic Condensed One',
  'Special Gothic Expanded One',
  'Spectral',
  'Spectral SC',
  'Spicy Rice',
  'Spinnaker',
  'Splash',
  'Spline Sans',
  'Spline Sans Mono',
  'Square Peg',
  'Sriracha',
  'Srisakdi',
  'Staatliches',
  'Stack Sans Headline',
  'Stack Sans Notch',
  'Stack Sans Text',
  'Stalemate',
  'Stalinist One',
  'Stick',
  'Stick No Bills',
  'Stint Ultra Condensed',
  'Stint Ultra Expanded',
  'Stoke',
  'Story Script',
  'Strait',
  'Strichpunkt Sans',
  'Style Script',
  'Suez One',
  'Sulphur Point',
  'Sumana',
  'Supermercado One',
  'Sura',
  'Swanky and Moo Moo',
  'Syncopate',
  'Syne',
  'Syne Mono',
  'Syne Tactile',
  'TASA Explorer',
  'TASA Orbiter',
  'Tac One',
  'Tagesschrift',
  'Tai Heritage Pro',
  'Tapestry',
  'Tauri',
  'Taviraj',
  'Teachers',
  'Teko',
  'Tektur',
  'Telex',
  'Tenor Sans',
  'Text Me One',
  'Texturina',
  'Thasadith',
  'The Girl Next Door',
  'The Nautigal',
  'TikTok Sans',
  'Tillana',
  'Tilt Neon',
  'Tilt Prism',
  'Tilt Warp',
  'Tinos',
  'Tiny5',
  'Tiro Bangla',
  'Tiro Devanagari Hindi',
  'Tiro Devanagari Marathi',
  'Tiro Devanagari Sanskrit',
  'Tiro Gurmukhi',
  'Tiro Kannada',
  'Tiro Tamil',
  'Tiro Telugu',
  'Tirra',
  'Titan One',
  'Titillium Web',
  'Tomorrow',
  'Tourney',
  'Train One',
  'Trirong',
  'Trispace',
  'Trocchi',
  'Truculenta',
  'Trykker',
  'Tsukimi Rounded',
  'Tuffy',
  'Turret Road',
  'Twinkle Star',
  'Ubuntu',
  'Ubuntu Condensed',
  'Ubuntu Mono',
  'Ubuntu Sans',
  'Ubuntu Sans Mono',
  'Ultra',
  'Unbounded',
  'Uncial Antiqua',
  'Underdog',
  'Unica One',
  'Unlock',
  'Unna',
  'Updock',
  'Urbanist',
  'VT323',
  'Vampiro One',
  'Varela',
  'Varela Round',
  'Varta',
  'Vazirmatn',
  'Vend Sans',
  'Vesper Libre',
  'Viaoda Libre',
  'Victor Mono',
  'Viga',
  'Vina Sans',
  'Voces',
  'Vollkorn',
  'Vollkorn SC',
  'Voltaire',
  'Vujahday Script',
  'WDXL Lubrifont JP N',
  'WDXL Lubrifont SC',
  'WDXL Lubrifont TC',
  'Waiting for the Sunrise',
  'Warnes',
  'Water Brush',
  'Waterfall',
  'Wellfleet',
  'Wendy One',
  'Whisper',
  'WindSong',
  'Winky Rough',
  'Winky Sans',
  'Wittgenstein',
  'Wix Madefor Display',
  'Wix Madefor Text',
  'Work Sans',
  'Xanh Mono',
  'Yaldevi',
  'Yanone Kaffeesatz',
  'Yantramanav',
  'Yatra One',
  'Yellowtail',
  'Yeseva One',
  'Yesteryear',
  'Yomogi',
  'Young Serif',
  'Yrsa',
  'Ysabeau',
  'Ysabeau Infant',
  'Ysabeau Office',
  'Ysabeau SC',
  'Yuji Boku',
  'Yuji Hentaigana Akari',
  'Yuji Hentaigana Akebono',
  'Yuji Mai',
  'Yuji Syuku',
  'Yusei Magic',
  'Zalando Sans',
  'Zalando Sans Expanded',
  'Zalando Sans SemiExpanded',
  'Zen Antique',
  'Zen Antique Soft',
  'Zen Dots',
  'Zen Kaku Gothic Antique',
  'Zen Kaku Gothic New',
  'Zen Kurenaido',
  'Zen Loop',
  'Zen Maru Gothic',
  'Zen Old Mincho',
  'Zen Tokyo Zoo',
  'Zeyada',
  'Zilla Slab',
  'Zilla Slab Highlight',
};
