name: Common Flutter Tasks

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner type'
        required: true
        default: 'ubuntu-latest'
        type: string

jobs:
  static-checks:
    runs-on: ${{ inputs.runner }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml
        cache: true
        pub-cache-key: "flutter-pub-:os:-:channel:-:version:-:arch:-${{ hashFiles('**/pubspec.lock') }}"

    - run: flutter --version # Print the Flutter version for debugging purposes

    - name: Install dependencies
      run: flutter pub get

    - name: Check for Outdated Dependencies
      run: flutter pub outdated

    - name: Run Flutter Analyze
      run: flutter analyze

    - name: Run Unit Tests
      run: flutter test