name: Flutter CI

on:
  push:
    branches: [ main, READ101-5-Configure-CI-CD-pipeline ]
  pull_request:
    branches: [ main, READ101-5-Configure-CI-CD-pipeline ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Clone repository
      uses: actions/checkout@v4 

    - name: Set up Flutter
      uses: subosito/flutter-action@v2 
      with:
        channel: stable 

    - run: flutter --version # Print the Flutter version for debugging purposes

    - name: Install dependencies
      run: flutter pub get

    - name: Run Flutter Analyze
      run: flutter analyze 
