name: Flutter CI

on:
  push:
    branches: [ main, READ101-5-Configure-CI-CD-pipeline ]
  pull_request:
    branches: [ main, READ101-5-Configure-CI-CD-pipeline ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Clone repository
      uses: actions/checkout@v4 
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2 
      with:
        channel: stable 

    - run: flutter --version # Print the Flutter version for debugging purposes

    - name: Cache Flutter Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.pub-cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Install dependencies
      run: flutter pub get

    - name: Check for Outdated Dependencies
      run: flutter pub outdated

    - name: Run Flutter Analyze
      run: flutter analyze 

    - name: Run Unit Tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk