name: Flutter Windows CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  common:
    uses: ./.github/workflows/common.yml
    with:
      runner: windows-latest

  windows-specific-steps:
    needs: common
    runs-on: windows-latest

    steps:
        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2 
      with:
        channel: stable

    - name: Cache Flutter Dependencies
      uses: actions/cache@v4
      with:
        path: C:\Users\runneradmin\AppData\Local\Pub\Cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: ${{ runner.os }}-flutter-

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows App
      run: flutter build windows --release

    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release.exe
        path: build/windows/runner/Release/